# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jlajCF18TdNdQaO_-xIioIn-iSCj4H1E
"""

import gradio as gr
import cv2
import numpy as np
import joblib
import tensorflow as tf
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
import base64
import os

#  Load models
RF_MODEL = joblib.load("models/rf_combined.pkl")
SCALER   = joblib.load("models/ml_scaler_combined.pkl")
DL_MODEL = tf.keras.models.load_model("models/mobilenet_final.keras")

# Feature extraction for Random Forest
def extract_features(img):
    features = []
    img_float = img.astype(np.float32) / 255.0
    for ch in range(3):
        features.append(img_float[:,:,ch].mean())
        features.append(img_float[:,:,ch].std())
    img_hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV).astype(np.float32)/255.0
    for ch in range(3):
        features.append(img_hsv[:,:,ch].mean())
        features.append(img_hsv[:,:,ch].std())
    img_lab = cv2.cvtColor(img, cv2.COLOR_RGB2LAB).astype(np.float32)/255.0
    for ch in range(3):
        features.append(img_lab[:,:,ch].mean())
        features.append(img_lab[:,:,ch].std())
    for ch in range(3):
        hist = cv2.calcHist([img], [ch], None, [32], [0,256])
        hist = hist.flatten() / hist.sum()
        features.extend(hist.tolist())
    return np.array(features, dtype=np.float32)

#  CLAHE preprocessing
def apply_clahe(img_rgb):
    img_bgr = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2BGR)
    img_bgr = cv2.resize(img_bgr, (224, 224))
    lab     = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    clahe   = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    l       = clahe.apply(l)
    img_bgr = cv2.merge([l, a, b])
    img_bgr = cv2.cvtColor(img_bgr, cv2.COLOR_LAB2BGR)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    return img_rgb

#  Grad-CAM
def get_gradcam_overlay(img_rgb):
    img_resized = cv2.resize(img_rgb, (224, 224))
    img_pre     = preprocess_input(img_resized.astype(np.float32))
    img_batch   = np.expand_dims(img_pre, axis=0)

    last_conv = None
    for layer in reversed(DL_MODEL.layers):
        if isinstance(layer, tf.keras.layers.Conv2D):
            last_conv = layer.name
            break

    grad_model = tf.keras.models.Model(
        inputs  = DL_MODEL.inputs,
        outputs = [DL_MODEL.get_layer(last_conv).output, DL_MODEL.output]
    )
    with tf.GradientTape() as tape:
        conv_out, pred = grad_model(img_batch)
        loss = pred[:, 0]

    grads   = tape.gradient(loss, conv_out)
    pooled  = tf.reduce_mean(grads, axis=(0,1,2))
    heatmap = conv_out[0] @ pooled[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0)
    heatmap = heatmap / (tf.math.reduce_max(heatmap) + 1e-8)
    heatmap = heatmap.numpy()

    hmap_r   = cv2.resize(heatmap, (224,224))
    hmap_u   = np.uint8(255 * hmap_r)
    hmap_c   = cv2.applyColorMap(hmap_u, cv2.COLORMAP_JET)
    hmap_rgb = cv2.cvtColor(hmap_c, cv2.COLOR_BGR2RGB)
    overlay  = cv2.addWeighted(img_resized, 0.6, hmap_rgb, 0.4, 0)

    return overlay, float(pred.numpy()[0][0])

# Main prediction functions
def predict_rf(image):
    """Random Forest prediction with CLAHE"""
    if image is None:
        return "Please upload an image.", None, ""

    img_rgb   = cv2.resize(np.array(image), (224, 224))
    img_clahe = apply_clahe(img_rgb)
    features  = extract_features(img_clahe)
    feat_sc   = SCALER.transform(features.reshape(1, -1))
    proba     = RF_MODEL.predict_proba(feat_sc)[0]
    pred      = int(RF_MODEL.predict(feat_sc)[0])
    conf      = float(proba[pred]) * 100
    label     = " ANEMIC" if pred == 1 else " NORMAL"

    result_text = f"""
## Result: {label}

**Confidence:** {conf:.1f}%
**Model:** Random Forest with CLAHE Features
**CV Accuracy:** 78.8% ± 1.8% (5-Fold Cross-Validation)

{' Hemoglobin likely below 12 g/dL. Consult a doctor.' if pred == 1 else ' Hemoglobin level appears normal.'}

---
 *This is a screening tool only , not a medical diagnosis.*
"""
    return result_text, img_clahe, f"{conf:.1f}% confident"

def predict_dl(image):
    """MobileNetV2 + Grad-CAM prediction"""
    if image is None:
        return "Please upload an image.", None, None, ""

    img_rgb  = cv2.resize(np.array(image), (224, 224))
    overlay, dl_pred = get_gradcam_overlay(img_rgb)

    label = " ANEMIC" if dl_pred > 0.5 else "NORMAL"
    conf  = (dl_pred if dl_pred > 0.5 else 1 - dl_pred) * 100

    result_text = f"""
## Result: {label}

**Confidence:** {conf:.1f}%
**Model:** MobileNetV2 + Grad-CAM
**Single-Split Accuracy:** 86.7%

{'Hemoglobin likely below 12 g/dL. Consult a doctor.' if dl_pred > 0.5 else ' Hemoglobin level appears normal.'}

---
 *This is a screening tool only — not a medical diagnosis.*
"""
    return result_text, overlay, img_rgb, f"{conf:.1f}% confident"

#  Gradio Interface
with gr.Blocks(
    title="Non-Invasive Anemia Detection",
    theme=gr.themes.Soft(primary_hue="blue"),
    css="""
    .header { text-align: center; padding: 20px; }
    .disclaimer { background: #fff3cd; padding: 12px;
                  border-radius: 8px; font-size: 13px; }
    """
) as demo:

    # Header
    gr.HTML("""
    <div class="header">
      <h1> Non-Invasive Anemia Detection</h1>
      <p>AI-powered conjunctival pallor analysis using Computer Vision & Transfer Learning</p>
      <p>
        <span style="background:#e3f2fd;padding:4px 10px;border-radius:99px;margin:3px;font-size:13px">Computer Vision</span>
        <span style="background:#f3e5f5;padding:4px 10px;border-radius:99px;margin:3px;font-size:13px">Transfer Learning</span>
        <span style="background:#e8f5e9;padding:4px 10px;border-radius:99px;margin:3px;font-size:13px">Grad-CAM XAI</span>
        <span style="background:#fff3e0;padding:4px 10px;border-radius:99px;margin:3px;font-size:13px">Eyes-Defy-Anemia Dataset</span>
      </p>
    </div>
    """)

    # Stats row
    with gr.Row():
        gr.Metric(label="Clinical Images", value="200")
        gr.Metric(label="RF CV Accuracy", value="78.8%")
        gr.Metric(label="Countries", value="2 (IT + IN)")
        gr.Metric(label="Models Compared", value="6")

    gr.Markdown("---")

    # Tabs for two modes
    with gr.Tabs():

        # Tab 1: Quick Analysis (RF)
        with gr.TabItem(" Quick Analysis (Random Forest)"):
            gr.Markdown("""
            **Most reliable mode.** Uses Random Forest with 114 CLAHE-enhanced color features.
            **78.8% accuracy** under 5-fold cross-validation on the Eyes-Defy-Anemia dataset.
            """)
            with gr.Row():
                with gr.Column(scale=1):
                    rf_input  = gr.Image(label="Upload Conjunctiva Image",
                                         type="pil", height=280)
                    rf_btn    = gr.Button("🔍 Analyze", variant="primary",
                                          size="lg")
                with gr.Column(scale=1):
                    rf_result = gr.Markdown(label="Result")
                    rf_clahe  = gr.Image(label="CLAHE Enhanced Image",
                                          height=200)
                    rf_conf   = gr.Textbox(label="Confidence", interactive=False)

            rf_btn.click(
                fn=predict_rf,
                inputs=[rf_input],
                outputs=[rf_result, rf_clahe, rf_conf]
            )

            gr.Examples(
                examples=[],
                inputs=rf_input
            )

        # Tab 2: Deep Analysis + Grad-CAM
        with gr.TabItem(" Deep Analysis + Grad-CAM (MobileNetV2)"):
            gr.Markdown("""
            **Visual explainability mode.** Uses MobileNetV2 pretrained on ImageNet, fine-tuned
            on conjunctiva images. Shows **Grad-CAM heatmap** — red regions indicate where the
            AI focused its attention. Best single-split accuracy: **86.7%**.
            """)
            with gr.Row():
                with gr.Column(scale=1):
                    dl_input = gr.Image(label="Upload Conjunctiva Image",
                                         type="pil", height=280)
                    dl_btn   = gr.Button(" Analyze + Show Grad-CAM",
                                          variant="primary", size="lg")
                with gr.Column(scale=1):
                    dl_result  = gr.Markdown(label="Result")
                    with gr.Row():
                        dl_original = gr.Image(label="Original", height=180)
                        dl_gradcam  = gr.Image(label="Grad-CAM Heatmap",
                                                height=180)
                    dl_conf = gr.Textbox(label="Confidence", interactive=False)

            dl_btn.click(
                fn=predict_dl,
                inputs=[dl_input],
                outputs=[dl_result, dl_gradcam, dl_original, dl_conf]
            )

    gr.Markdown("---")

    # About section
    with gr.Accordion(" About This Project", open=False):
        gr.Markdown("""
        ## Non-Invasive Anemia Detection using Transfer Learning

        Anemia affects **1 billion+ people worldwide**. Traditional diagnosis requires
        invasive blood tests. This system analyzes the **palpebral conjunctiva** (inner
        lower eyelid) — which becomes pale in anemic patients — using only a smartphone photo.

        ### How it works
        1. Upload a photo of the inner lower eyelid (palpebral conjunctiva)
        2. The AI applies CLAHE contrast enhancement and extracts color features
        3. Random Forest or MobileNetV2 predicts Anemic / Normal
        4. Grad-CAM shows which regions the AI focused on

        ### Dataset
        - **Eyes-Defy-Anemia** — 200 patients, Italy + India
        - Ground-truth hemoglobin values (Hgb < 12 g/dL = Anemic)
        - Published by Dimauro et al., *AI in Medicine* (2023)

        ### Key Research Findings
        - CLAHE improves ML but degrades DL (preprocessing distribution shift)
        - Random Forest (78.8% CV) outperforms MobileNetV2 (63.0% CV) on 200 images
        - Domain shift confirmed when combining heterogeneous conjunctiva datasets
        - Grad-CAM validates clinically relevant attention regions


        """)

    # Disclaimer
    gr.HTML("""
    <div class="disclaimer">
        <strong>⚠️ Medical Disclaimer:</strong> This application is for
        educational and research purposes only. It is <strong>not</strong>
        a substitute for professional medical diagnosis. Always consult a
        qualified healthcare provider for medical concerns.
    </div>
    """)

# Launch
if __name__ == "__main__":
    demo.launch()